### ISSUE TITLE
New include for Deviantart

### ISSUE THREAD

**Issue by Liandriz** [TimidScript/UserScripts#3]
Hi, is this possible to add pagination to the "new" feature, _morelikethis_,
like this pattern : _://_.deviantart.com/morelikethis/\* ?

And another one for Deviantart, is this possible to add an _int_ value to autoload the first XX pages of listings?

Thanks,
Liandri.

**Comment by TimidScript** [comment]
H Liandri,

> new" feature, morelikethis, like this pattern : ://.deviantart.com/morelikethis/\* ?

It already has pagination. You enable it by pressing the `show more` button. Not sure what you want here.

> And another one for Deviantart, is this possible to add an int value to autoload the first XX pages of listings?

Snap(ish). I added something similar to Pixiv++ beta version; buttons that allows you to load X number of pages on demand rather than scroll. I will try include your request in the next release. As it's not a script a bug, it will have to wait until I finish higher priority scripts/issues.

**Comment by Liandriz** [comment]
Thanks for adding it as next feature, for preloading X pages!

For the _show more_ button, i'm using your script to grab posts with the Firefox addon ImageHostGrabber, and it seems it can't find posts with the _show more_ option, but works like a charm with your pagination, that's why i just asked for it :p

**Comment by TimidScript** [comment]
@Liandrizm

The "Show More" button works exactly the same way as I would encode it. The placement would be different, but it's more or less the same. I do not know how the images/posts are grabbed by the script (couldn't find it) or the FF extension, but the problem lies with them. I guess their selector is too specific when trying to get the thumbnails. A change of one or two lines from their end should fix the issue.

**Comment by TimidScript** [comment]
I forgot about this for a long while. I finally got to it and did a quick fix. 

Search for the following line `//GM_setValue("ScrollOffset", 500); //The gap between page loading` and uncomment it and then change the 500 value to something you want. This is the scroll gap between page loading. The larger the gap the more pages it loads as you scroll to page loading trigger. Set it high, say 2000 and then you would always have around 3 pages loaded underneath.
